# Generated by Django 6.0.5 on 2026-05-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pagador', models.CharField(max_length=512, verbose_name='Nome do pagador')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data de baixa')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento')),
                ('nosso_numero', models.CharField(max_length=64, verbose_name='Nosso número')),
                ('seu_numero', models.CharField(max_length=64, verbose_name='Seu número')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('identificacao', models.CharField(max_length=128, verbose_name='Identificação')),
                ('parcela', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Parcela')),
                ('total_parcelas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total de parcelas')),
                ('codigo_pagador', models.CharField(max_length=16, verbose_name='Código pagador')),
                ('valor_liquidacao_titulo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Liquidacao Titulo')),
                ('quitado_com_boleto', models.ForeignKey(blank=True, help_text='Indique o boleto que quita esse valor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boletos.boleto')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
    ]
