# Generated by Django 6.0.4 on 2026-05-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='valor_liquidacao_titulo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Liquidacao Titulo'),
        ),
    ]
