# Generated by Django 6.0.5 on 2026-05-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='considerar_pago',
            field=models.BooleanField(default=False, verbose_name='Considerar Pago'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
