# Generated by Django 6.0.5 on 2026-05-17 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0002_alter_boleto_valor_liquidacao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='quitado_com_boleto',
            field=models.ForeignKey(blank=True, help_text='Indique o boleto que quita esse valor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='boletos.boleto'),
        ),
    ]
