# Generated by Django 6.0.5 on 2026-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descrição')),
                ('documento', models.CharField(blank=True, max_length=64, null=True, verbose_name='Documento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimento',
            },
        ),
    ]
